# Generated by Django 2.2.27 on 2023-03-21 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clip',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(default='', max_length=20)),
                ('tv_id', models.CharField(default='', max_length=20)),
                ('docs', models.CharField(default='', max_length=200, verbose_name='docs')),
                ('tv', models.FileField(default='', upload_to='tvfile')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='create_time')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='updated_time')),
            ],
            options={
                'db_table': 'clip',
            },
        ),
        migrations.CreateModel(
            name='tv',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titile', models.CharField(default='', max_length=200, verbose_name='titile')),
                ('docs', models.CharField(default='', max_length=200, verbose_name='docs')),
                ('img', models.ImageField(default='', upload_to='tvimg')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='create_time')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='updated_time')),
            ],
            options={
                'db_table': 'tv',
            },
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='', max_length=20, verbose_name='username')),
                ('password', models.CharField(default='', max_length=20, verbose_name='password')),
                ('img', models.ImageField(default='img/images.png', upload_to='img')),
                ('email', models.CharField(default='', max_length=20, verbose_name='email')),
                ('bio', models.CharField(default='', max_length=200, verbose_name='')),
                ('favourite_shows', models.CharField(default='', max_length=200, verbose_name='')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='create_time')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='updated_time')),
            ],
            options={
                'verbose_name_plural': 'user',
                'db_table': 'user',
            },
        ),
    ]
