# Generated by Django 2.2.28 on 2023-03-21 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showtalk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clip',
            name='extension',
            field=models.CharField(default='mp4', max_length=8),
            preserve_default=False,
        ),
    ]
