# Generated by Django 2.2.27 on 2023-03-21 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showtalk', '0003_auto_20230321_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='pl',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(default='', max_length=20)),
                ('tv_id', models.CharField(default='', max_length=20)),
                ('doc', models.TextField()),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='create_time')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='updated_time')),
            ],
            options={
                'db_table': 'pl',
            },
        ),
        migrations.DeleteModel(
            name='clip',
        ),
        migrations.RemoveField(
            model_name='tv',
            name='titile',
        ),
        migrations.AddField(
            model_name='tv',
            name='title',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='tv',
            name='tv',
            field=models.FileField(default='tv/demo.mp4', upload_to='tv'),
        ),
        migrations.AddField(
            model_name='tv',
            name='user_id',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='tv',
            name='img',
            field=models.ImageField(default='img/images.png', upload_to='img'),
        ),
    ]
